### ISSUE TITLE
Purpose of this extension in TER?

### ISSUE THREAD

**Issue by spoonerWeb** [visuellverstehen/t3visuellverstehen#1]
My main question is why you published this extension in TER?
I would understand it if it's possible to configure the support contact information so everybody can use it for their customers.
But it shows only the contact information of your agency, right?
If yes, it has no value for the TYPO3 community imho.

**Comment by malteriechmann** [comment]
> But it shows only the contact information of your agency, right?

You are right.

I guess we publish it in TER, because back in the days Composer was not the default/only way of installing extensions. And we wanted to install/update this extension in some client projects without Composer.

But sure, it has no huge value for the TYPO3 community. Maybe one can have a look and be inspired in creating something similar.

Nevertheless I will check on this and turn off TER deployment, if it is not needed anymore.

**Comment by machwatt** [comment]
Maybe it is possible to make these infos editable maybe with constant manager? Would take a look on it, if appreciated.

**Comment by malteriechmann** [comment]
@machwatt I cannot really think of a good place for those informations. Site configuration is for sites, not the complete TYPO3 backend. TypoScript constants are kind of legacy, at least I would like to avoid using them.

Also I would like to have no manual setup steps. The developer should just install the extension and go for it.

**Comment by machwatt** [comment]
Then this extension should not be public availabz I think ;)

**Comment by malteriechmann** [comment]
>Then this extension should not be public availabz I think ;)

Atleast not in TER.

>Would take a look on it, if appreciated.

If you want to create a similar extension with editable informations, feel free to fork.

**Comment by runepiper** [comment]
I marked the extension as abandoned in TER and marked it as internal in README.
